groups:
  - name: portal-ui-cypress
    jobs:
      - run-cypress-tests-parallel
       
  - name: update-pipeline
    jobs:
      - update-pipeline


resource_types:
- name: time
  type: registry-image
  source:
    repository: concourse/time-resource

- name: git
  type: registry-image
  source:
    repository: concourse/git-resource
    username: ((docker.username))
    password: ((docker.password))
    
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    username: ((docker.username))
    password: ((docker.password))
    tag: latest

resources:
# Cypress
- name: daily-schedule
  type: time
  check_every: 30s
  source:
    interval: 24h
    start: "02:00 AM"
    stop: "03:00 AM"
    location: "America/Toronto"
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

- name: slack-alert-cypress
  type: slack-notification
  source:
    url: ((slack.webhook-url-cypress))

- name: minio-storage
  type: s3
  source:
    endpoint: https://s3.cqgc.hsj.rtss.qc.ca
    bucket: cqgc-qa-cypress-tests
    access_key_id: "((minio.access_key))"
    secret_access_key: ((minio.secret_key))
    use_ssl: false  # Set to true if MinIO is configured with SSL
    regexp: test-results/merged-results-.*\.xml
    
- name: git-portal-ui
  type: git
  icon: github
  check_every: 30s
  webhook_token: ((webhook-token))
  source:
    uri: git@github.com:Ferlab-Ste-Justine/clin-portal-ui.git
    branch: main
    private_key: ((git.portal-ssh-key))
    # ignore_paths: [ci/]

- name: ci-folder
  type: git
  check_every: 30s
  source:
    uri: git@github.com:Ferlab-Ste-Justine/clin-portal-ui.git
    branch: main
    paths: [ci]
    private_key: ((git.portal-ssh-key))


jobs:
- name: run-cypress-tests-parallel
  plan:
  - get: daily-schedule
    trigger: true
  - get: git-portal-ui
    trigger: false
    params:
      submodule_recursive: true

  - in_parallel:
      fail_fast: false
      steps:

      - task: cypress-parallel-1
        attempts: 6
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ferlabcrsj/cypress-included-custom
              tag: latest
          inputs:
            - name: git-portal-ui
          outputs:
            - name: test-results-1
          params:
            CYPRESS_PASSWORD: ((cypress.password))
          run:
            path: bash
            args:
              - -c
              - |
                set +e 
                pushd git-portal-ui
                npm install
                cp env-qa .env
                sed -i 's/CYPRESS_PASSWORD=""/CYPRESS_PASSWORD="'$CYPRESS_PASSWORD'"/' .env
                npx cypress run --config-file cypress.config.ts --config retries=5 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-1/results-[hash].xml" --spec "cypress/e2e/Consultation/TableauVariantsPatient_3.cy.ts,cypress/e2e/Consultation/TableauRequetes.cy.ts,cypress/e2e/Filtres/PageVariantsPatient.cy.ts,cypress/e2e/Consultation/TableauVariantsPatient_2.cy.ts,cypress/e2e/Consultation/TableauFichiers.cy.ts,cypress/e2e/Facettes/PageVariants.cy.ts,cypress/e2e/Consultation/TableauVariantsPatientPaired_1.cy.ts,cypress/e2e/Consultation/PageAnalyseBioinfo.cy.ts,cypress/e2e/Colonnes/TableauRequetes.cy.ts,cypress/e2e/Telechargement/TableauVariantsPatientPaired.cy.ts,cypress/e2e/Telechargement/TableauVariantsPatientSomatic.cy.ts,cypress/e2e/Colonnes/TableauCNVsPatientSomatic.cy.ts,cypress/e2e/Consultation/PageAnalyseBioinfoPaired.cy.ts,cypress/e2e/Recherches/PageArchives.cy.ts,cypress/e2e/Colonnes/TableauArchives.cy.ts,cypress/e2e/Navigation/Logout.cy.ts,cypress/e2e/Requetes/ActionsSurCombinaison.cy.ts,cypress/e2e/Recherches/PagePrescriptions.cy.ts,cypress/e2e/Telechargement/RapportCouvertureGenique.cy.ts,cypress/e2e/Telechargement/RapportGeneral.cy.ts,cypress/e2e/Telechargement/RapportVariantPatient.cy.ts,cypress/e2e/Telechargement/RapportVariantPatientSomatic.cy.ts,cypress/e2e/IGV/TableauCNVsPatientSomatic.cy.ts,cypress/e2e/IGV/TableauCouvertureGenique.cy.ts,cypress/e2e/IGV/TableauVariantsPatient.cy.ts,cypress/e2e/IGV/TableauVariantsPatientPaired.cy.ts,cypress/e2e/IGV/TableauVariantsPatientSomatic.cy.ts"
                
                # Run only the first Cypress test
                # FIRST_TEST=$(ls cypress/e2e/**/*.cy.{js,jsx,ts,tsx} | head -n 1)
                # npx cypress run --config-file cypress.config.ts --config retries=2 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-1/results-[hash].xml" --spec "$FIRST_TEST"
             
                popd
                exit 0

      - task: cypress-parallel-2
        attempts: 6
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ferlabcrsj/cypress-included-custom
              tag: latest
          inputs:
            - name: git-portal-ui
          outputs:
            - name: test-results-2
          params:
            CYPRESS_PASSWORD: ((cypress.password))
          run:
            path: bash
            args:
              - -c
              - |
                set +e 
                pushd git-portal-ui
                npm install
                cp env-qa .env
                sed -i 's/CYPRESS_PASSWORD=""/CYPRESS_PASSWORD="'$CYPRESS_PASSWORD'"/' .env
                npx cypress run --config-file cypress.config.ts --config retries=5 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-2/results-[hash].xml" --spec "cypress/e2e/Requetes/ValidationVariantsPatient.cy.ts,cypress/e2e/Facettes/PageVariantsPatient_4.cy.ts,cypress/e2e/Consultation/TableauVariantsPatientPaired_3.cy.ts,cypress/e2e/Consultation/TableauPrescriptions.cy.ts,cypress/e2e/Filtres/PageVariantsPatientPaired.cy.ts,cypress/e2e/Consultation/TableauCouvertureGenique.cy.ts,cypress/e2e/Consultation/TableauCNVsPatientSomatic.cy.ts,cypress/e2e/Facettes/PageCNVsPatient.cy.ts,cypress/e2e/Consultation/TableauVariantsPatientPaired_2.cy.ts,cypress/e2e/UploadList/PageVariantsPatientPaired.cy.ts,cypress/e2e/Facettes/PagePrescriptions.cy.ts,cypress/e2e/Facettes/PageVariantsPatient_2.cy.ts,cypress/e2e/Facettes/DictionnairesCNVsPatient.cy.ts,cypress/e2e/Consultation/PagePrescription.cy.ts,cypress/e2e/Consultation/TableauVariantsPatientSomatic_1.cy.ts,cypress/e2e/Facettes/PageVariantsPatientSomatic.cy.ts,cypress/e2e/Colonnes/TableauVariantsPatient.cy.ts,cypress/e2e/Consultation/TableauVariants_1.cy.ts,cypress/e2e/Colonnes/TableauCNVsPatient.cy.ts,cypress/e2e/Telechargement/TableauCouvertureGenique.cy.ts,cypress/e2e/Telechargement/TableauVariants.cy.ts,cypress/e2e/Colonnes/TableauPrescriptions.cy.ts,cypress/e2e/Facettes/PageVariantsPatient_1.cy.ts,cypress/e2e/Telechargement/Panels.cy.ts,cypress/e2e/Navigation/Login.cy.ts"
                
                # Run only the first Cypress test
                # FIRST_TEST=$(ls cypress/e2e/**/*.cy.{js,jsx,ts,tsx} | head -n 1)
                # npx cypress run --config-file cypress.config.ts --config retries=2 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-2/results-[hash].xml" --spec "$FIRST_TEST"
             
                popd
                exit 0
      - task: cypress-parallel-3
        attempts: 6
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ferlabcrsj/cypress-included-custom
              tag: latest
          inputs:
            - name: git-portal-ui
          outputs:
            - name: test-results-3
          params:
            CYPRESS_PASSWORD: ((cypress.password))
          run:
            path: bash
            args:
              - -c
              - |
                set +e 
                pushd git-portal-ui
                npm install
                cp env-qa .env
                sed -i 's/CYPRESS_PASSWORD=""/CYPRESS_PASSWORD="'$CYPRESS_PASSWORD'"/' .env
                npx cypress run --config-file cypress.config.ts --config retries=5 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-3/results-[hash].xml" --spec "cypress/e2e/Consultation/TableauVariantsPatientSomatic_2.cy.ts,cypress/e2e/Consultation/PageVariantResume.cy.ts,cypress/e2e/Consultation/TableauVariantsPatientSomatic_3.cy.ts,cypress/e2e/Facettes/DictionnairesVariantsPatient.cy.ts,cypress/e2e/Filtres/PageVariantsPatientSomatic.cy.ts,cypress/e2e/Filtres/PageVariants.cy.ts,cypress/e2e/AccesUtilisateurs/ParRole.cy.ts,cypress/e2e/Facettes/PageVariantsPatient_3.cy.ts,cypress/e2e/UploadList/PageVariantsPatient.cy.ts,cypress/e2e/UploadList/PageVariantsPatientSomatic.cy.ts,cypress/e2e/Consultation/TableauArchives.cy.ts,cypress/e2e/Consultation/TableauVariants_2.cy.ts,cypress/e2e/Consultation/TableauVariantsPatient_1.cy.ts,cypress/e2e/Consultation/PageVariantPatients.cy.ts,cypress/e2e/Consultation/TableauxRapportGeneralSomatic.cy.ts,cypress/e2e/Facettes/PageVariantsPatientPaired.cy.ts,cypress/e2e/Telechargement/TableauVariantsPatient.cy.ts,cypress/e2e/Consultation/PageAnalyseBioinfoSomatic.cy.ts,cypress/e2e/Telechargement/TableauCNVsPatient.cy.ts,cypress/e2e/Colonnes/TableauVariants.cy.ts,cypress/e2e/Colonnes/TableauCouvertureGenique.cy.ts,cypress/e2e/Colonnes/TableauFichiers.cy.ts,cypress/e2e/Requetes/ActionsSur1Requete2Pilules.cy.ts,cypress/e2e/Consultation/TiroirOccurrenceSomatic.cy.ts,cypress/e2e/Navigation/Landing.cy.ts"

                # Run only the first Cypress test
                # FIRST_TEST=$(ls cypress/e2e/**/*.cy.{js,jsx,ts,tsx} | head -n 1)
                # npx cypress run --config-file cypress.config.ts --config retries=2 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-3/results-[hash].xml" --spec "$FIRST_TEST"
             
                popd
                exit 0
      - task: cypress-parallel-4
        attempts: 6
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ferlabcrsj/cypress-included-custom
              tag: latest
          inputs:
            - name: git-portal-ui
          outputs:
            - name: test-results-4
          params:
            CYPRESS_PASSWORD: ((cypress.password))
          run:
            path: bash
            args:
              - -c
              - |
                set +e
                pushd git-portal-ui
                npm install
                cp env-qa .env
                sed -i 's/CYPRESS_PASSWORD=""/CYPRESS_PASSWORD="'$CYPRESS_PASSWORD'"/' .env
                npx cypress run --config-file cypress.config.ts --config retries=5 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-4/results-[hash].xml" --spec "cypress/e2e/Recherches/PageAccueil.cy.ts,cypress/e2e/Consultation/TableauVariants_3.cy.ts,cypress/e2e/Facettes/DictionnairesVariants.cy.ts,cypress/e2e/Filtres/PageCNVsPatientSomatic.cy.ts,cypress/e2e/Filtres/PageCNVsPatient.cy.ts,cypress/e2e/Consultation/TableauCNVsPatient.cy.ts,cypress/e2e/Facettes/PageVariantsPatient_5.cy.ts,cypress/e2e/UploadList/PageVariants.cy.ts,cypress/e2e/Facettes/PageVariantsPatient_6.cy.ts,cypress/e2e/Consultation/TableauGenesChevauchantsCNV.cy.ts,cypress/e2e/Recherches/TableauCouvertureGenique.cy.ts,cypress/e2e/Requetes/ActionsSur2Requetes.cy.ts,cypress/e2e/Consultation/TableauxRapportGeneral.cy.ts,cypress/e2e/Requetes/ActionsSur1Requete1Pilule.cy.ts,cypress/e2e/Navigation/Pages.cy.ts,cypress/e2e/Telechargement/TableauCNVsPatientSomatic.cy.ts,cypress/e2e/Colonnes/TableauVariantsPatientPaired.cy.ts,cypress/e2e/Consultation/TiroirOccurrence.cy.ts,cypress/e2e/Colonnes/TableauVariantsPatientSomatic.cy.ts,cypress/e2e/Telechargement/TableauRequetes.cy.ts,cypress/e2e/Telechargement/TableauPrescriptions.cy.ts,cypress/e2e/Consultation/TableauCouvertureGeniqueSomatic.cy.ts,cypress/e2e/Consultation/TiroirOccurrencePaired.cy.ts,cypress/e2e/Requetes/ActionsSur0Requete.cy.ts,cypress/e2e/Navigation/Variants.cy.ts,cypress/e2e/Telechargement/RapportVariantPatientPaired.cy.ts,cypress/e2e/IGV/TableauCNVsPatient.cy.ts"

                # Run only the first Cypress test
                # FIRST_TEST=$(ls cypress/e2e/**/*.cy.{js,jsx,ts,tsx} | head -n 1)
                # npx cypress run --config-file cypress.config.ts --config retries=2 --browser chrome --reporter junit --reporter-options "mochaFile=../test-results-4/results-[hash].xml" --spec "$FIRST_TEST"
             
                popd
                exit 0
                
  - task: merge-results
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ferlabcrsj/cypress-included-custom
          tag: latest
      inputs:
        - name: test-results-1
        - name: test-results-2
        - name: test-results-3
        - name: test-results-4
      outputs:
        - name: merged-results
        - name: timestamp
      run:
        path: bash
        args:
          - -c
          - |
            set -e # Exit on error
            mkdir -p merged-results
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            echo $TIMESTAMP > timestamp/timestamp.txt
            npx junit-merge test-results-1/*.xml test-results-2/*.xml test-results-3/*.xml test-results-4/*.xml -o merged-results/merged-results-${TIMESTAMP}.xml

  - put: minio-storage
    attempts: 3
    params:
      file: merged-results/merged-results-*.xml
    no_get: true

  - task: generate-presigned-url
    attempts: 3
    params:
      MINIO_ACCESS_KEY: ((minio.access_key))
      MINIO_SECRET_KEY: ((minio.secret_key))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ferlabcrsj/cypress-included-custom
          tag: latest
      inputs:
        - name: merged-results
        - name: timestamp
      outputs:
        - name: slack-data
      run:
        path: bash
        args:
          - -c
          - |
            set -e  # Exit on error

            # Read the timestamp
            TIMESTAMP=$(cat timestamp/timestamp.txt)

            # Check if the merged results file is not empty
            if [ -s merged-results/merged-results-${TIMESTAMP}.xml ]; then
              # Generate a pre-signed URL
              mc alias set myminio https://s3.cqgc.hsj.rtss.qc.ca $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
              PRESIGNED_URL=$(mc share download myminio/cqgc-qa-cypress-tests/test-results/merged-results-${TIMESTAMP}.xml --expire=48h | grep -oP '(?<=Share: ).*')

              # Prepare Slack message for success
              echo '[
                {
                  "color": "good",
                  "title": "Portal UI Cypress Test Results",
                  "text": "Cypress test results are available for Portal UI. <'$PRESIGNED_URL'|View Results>"
                }
              ]' > slack-data/attachments.json
            else
              # Prepare Slack message for absence of results
              echo '[
                {
                  "color": "warning",
                  "title": "Portal UI Cypress Test Results",
                  "text": "No test results are available for Portal UI due to an error or no tests were executed."
                }
              ]' > slack-data/attachments.json
            fi

  - put: slack-alert-cypress
    params:
      attachments_file: slack-data/attachments.json

- name: update-pipeline
  plan:
    - get: ci-folder
      trigger: true
    - set_pipeline: self
      file: ci-folder/ci/pipeline.yml