/// <reference types="cypress"/>
export const data = {
    variantGermline: {
      dataRowKey: '4577893f4d3c2463e9fdef3419f7781d00fffdf3',
      variant: 'chrX:g.123403094G>A',
      type: 'SNV',
      dbsnp: 'rs138817389',
      gene: 'GRIA3',
      consequence: 'Missense p.Arg394Gln',
      consequenceImpact: 'ConsequencesCell_moderateImpact',
      maneC: true,
      maneM: true,
      maneP: false,
      omim: 'XLR',
      omimID: '305915',
      clinvar: ['B', 'LB'],
      clinvarID: '198752',
      gnomad: '1.02e-3',
      gnomad_alt: 1060,
      rqdmP: 6,
      rqdmF: 'e-2',
      cmcP: 3,
      cmcF: '6.93e-5',
      cmcID: 'COSV52051792',
      hotspot: '-',
      exomiser_var: '0.9436',
      tier: 'Other',
      max_franklin: '-',
      max_exomiser: '0.964',
      acmg_franklin: 'ND',
      acmg_exomiser: 'VUS',
      criteria_franklin: '-',
      cadd: '2.56e+1',
      revel: '-',
      franklin: '-',
      exomiser: '0.964',
      qg: '170',
      cnvs: 0,
      zygosity: 1,
      genotypes: '0/1 : 0',
      hc: '-',
      hcp: '-',
      transmission: 'XLR',
      qp: '0.97',
      op: 'M',
      a: '84',
      a_r: '84',
      a_ratio: '1.00',
      filter: 'PASS',
      criteria_exomiser: 'PP4, BP6_Strong',
    },
  };
